language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  - "nightly"
before_install:
  - sudo apt -qq update
  - pip install -U pip setuptools wheel
install:
  - sudo apt -qq install aria2
  - pip install -Ur requirements.txt
  - pip install -U flake8 pytest-cov
script:
  - flake8
  - pytest
after_success:
  - codecov
